name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    environment: homolog

    steps:
    - uses: actions/checkout@v3

    - name: Show files
      run: "ls -la"

    - name: print secrets
      run: |
          echo $DEV_ENV_FILE &gt;&gt; .env
          cat .env
      shell: bash
      env:
        DEV_ENV_FILE : ${{secrets.CONFIG_DOTENV}}

    - name: Show files
      run: "ls -la"

    - name: Show .env
      run: "cat .env"
