name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  continuous-deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    environment: homolog

    steps:
    - uses: actions/checkout@v3

    - name: Show files
      run: "ls -la"

    - name: Show .env
      run: "echo ${{ secrets.CONFIG_DOTENV }} > .env"

    - name: Show files
      run: "ls -la"
